### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by tafaquh** [rizaumami/kbbi#2]
file J.txt is empty. Do you have the complete one?

**Comment by rizaumami** [comment]
There is no J and P entries on Kamus-Besar-Bahasa-Indonesia.pdf or Lema_Tertinggal_KBBI_Ed._Keempat_Rev_Ver_4.pdf.

**Comment by tafaquh** [comment]
Oh my bad. Thank you sir. 
Maybe you have another references?

**Comment by rizaumami** [comment]
Hampir tiga tahun berselang...
Ternyata lema P ada dalam berkas [Lema_Tertinggal_KBBI_Ed._Keempat_Rev_Ver_4.pdf](https://github.com/rizaumami/kbbi/blob/master/sumber/Lema_Tertinggal_KBBI_Ed._Keempat_Rev_Ver_4.pdf).

Teks akhir akan diperbaharui dalam waktu dekat.
